### ISSUE TITLE
Error when running in node 

### ISSUE THREAD

**Issue by havascolino** [joaompneves/tsviz#19]
I installed graphviz 2.38 and added to path get this error message

D:\tsviz>tsviz app.component.ts v.png
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:953:11)
    at Socket._writeGeneric (net.js:705:26)
    at Socket._write (net.js:724:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:650:40)
    at Graph.render (C:\Users\Administrator\AppData\Roaming\npm\node_modules\tsv
iz\node_modules\graphviz\lib\deps\graph.js:380:18)
    at Graph.output (C:\Users\Administrator\AppData\Roaming\npm\node_modules\tsv
iz\node_modules\graphviz\lib\deps\graph.js:385:8)
    at Object.buildUml (C:\Users\Administrator\AppData\Roaming\npm\node_modules\
tsviz\bin\uml-builder.js:30:7)

D:\tsviz>

**Comment by joaompneves** [comment]
Check if graphviz folder is set on your PATH variable. If not, you should add folder of gvpr.exe (usually %Graphviz_folder%/bin) to the PATH variable.

**Comment by havascolino** [comment]
Dear Joao,Thank you for your help . After adding the bin to the path I get a done message in most cases but no one is created the only image created when my dir path points to the examples dir in your node module. I am trying to model angular 2 projects some times I get a can not read property forEa CV h of undefined. I never get a PNG. I guess this has some thing to do with dependency scrolling.
Ariel

Sent from Yahoo Mail on Android 

  On יום ד׳, אוג׳ 24, 2016 at 19:41, João Nevesnotifications@github.com wrote:  
Check if graphviz folder is set on your PATH variable. If not, you should add folder of gvpr.exe (usually %Graphviz_folder%/bin) to the PATH variable.

**Comment by havascolino** [comment]
Dear Joao,
Here is the error message
D:\tsviz>tsviz app\  app.png
'app\' does not exist
C:\Users\Administrator\AppData\Roaming\npm\node_modules\tsviz\bin\uml-builder.js
:18
    modules.forEach(function (module) {
           ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.buildUml (C:\Users\Administrator\AppData\Roaming\npm\node_modules\
tsviz\bin\uml-builder.js:18:12)
    at Object.createGraph (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\tsviz\bin\tsviz.js:36:16)
    at main (C:\Users\Administrator\AppData\Roaming\npm\node_modules\tsviz\bin\t
sviz-app.js:16:11)
    at Object.run (C:\Users\Administrator\AppData\Roaming\npm\node_modules\tsviz
\bin\tsviz-app.js:20:5)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modul
es\tsviz\bin\tsviz-main.js:4:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

D:\tsviz>tsviz D:\angular2-tour-of-heroes\app\  tour_of_heros.png
done

D:\tsviz>

 Ariel Wassertheil

```
On Wednesday, August 24, 2016 7:41 PM, João Neves <notifications@github.com> wrote:
```

 Check if graphviz folder is set on your PATH variable. If not, you should add folder of gvpr.exe (usually %Graphviz_folder%/bin) to the PATH variable.—

**Comment by joaompneves** [comment]
Can you try with the latest tsviz version? I tried running against that example (from here: https://github.com/johnpapa/angular2-tour-of-heroes) and it generates the diagram.

**Comment by Exclaminator** [comment]
When I got this error it seemed that my installation path of Graphviz was wrong, fixed it with
`ln -s /usr/bin/dot /usr/local/bin/dot`
