### ISSUE TITLE
Error: Could not find Graphviz in PATH.

### ISSUE THREAD

**Issue by bennycode** [joaompneves/tsviz#24]
Hello, today I installed Graphviz v2.38 (using `graphviz-2.38.msi`) on Windows 10. Afterwards I tried to run `tsviz src/ diagram.png` but I only receive this error message:

> Could not find Graphviz in PATH.
events.js:160
      throw er; // Unhandled 'error' event
      ^
> Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at Socket._writeGeneric (net.js:712:26)
    at Socket._write (net.js:731:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Socket.Writable.write (_stream_writable.js:247:11)
    at Socket.write (net.js:658:40)
    at Graph.render (C:\Users\Benny\AppData\Roaming\npm\node_modules\tsviz\node_modules\graphviz\lib\deps\graph.js:380:18)
    at Graph.output (C:\Users\Benny\AppData\Roaming\npm\node_modules\tsviz\node_modules\graphviz\lib\deps\graph.js:385:8)
    at Object.buildUml (C:\Users\Benny\AppData\Roaming\npm\node_modules\tsviz\bin\uml-builder.js:30:7)

So it looks like your tool cannot find **Graphviz**. Do I need to add a specific `.exe` to my system variables?

**Comment by khanrezwan** [comment]
I am also facing this error on Ubuntu14.04LTS.
`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/bin/dot ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
`

**Comment by fase** [comment]
Just had this issue on Windows and resolved it by adding C:\Program Files (x86)\Graphviz2.38\bin to my PATH environment variable.  Worked fine after that.

**Comment by SjoCi** [comment]
After inserting to PATH don't forget to Sign out and in for windows to reload the environment variables, it will save you a lot of rage and time. Just saying... no real experience... (17 minutes...)

**Comment by Exclaminator** [comment]
When I got this error it seemed that my installation path of Graphviz was wrong, fixed it with 
`ln -s /usr/bin/dot /usr/local/bin/dot`
