### ISSUE TITLE
Found 0 module(s), events.js:160, throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by kiewic** [joaompneves/tsviz#25]
What does it mean the following error?

```
Found 0 module(s)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1018:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Socket.Writable.write (_stream_writable.js:247:11)
    at Socket.write (net.js:661:40)
    at Graph.render (C:\Users\me\AppData\Roaming\npm\node_modules\tsviz\node_modules\graphviz\lib\deps\graph.js:380:18)
    at Graph.output (C:\Users\me\AppData\Roaming\npm\node_modules\tsviz\node_modules\graphviz\lib\deps\graph.js:385:8)
    at Object.buildUml (C:\Users\me\AppData\Roaming\npm\node_modules\tsviz\bin\uml-builder.js:30:7)```

Is having zero modules an error?

The command I ran was:

```winbash
tsviz c:\myProject diagram.png
```

If I add `-recursive`, then the error becomes:

```
Found 234 module(s)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1018:11)
    at Socket._writeGeneric (net.js:715:26)
    at Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at Socket.Writable.write (_stream_writable.js:247:11)
    at Socket.write (net.js:661:40)
    at Graph.render (C:\Users\me\AppData\Roaming\npm\node_modules\tsviz\node_modules\graphviz\lib\deps\graph.js:380:18)
    at Graph.output (C:\Users\me\AppData\Roaming\npm\node_modules\tsviz\node_modules\graphviz\lib\deps\graph.js:385:8)
    at Object.buildUml (C:\Users\me\AppData\Roaming\npm\node_modules\tsviz\bin\uml-builder.js:30:7)

```

**Comment by kiewic** [comment]
Sample also fails with the same error, could it be an OS issue?

**Comment by kiewic** [comment]
Never mind, I found the problem. I had the wrong Graphviz directory in the path. I had added `C:\Program Files (x86)\Graphviz2.38` instead of `C:\Program Files (x86)\Graphviz2.38\bin`.

Now tsviz is working!

**Comment by tomdavidson** [comment]
same here on linux, but graphviz is in a known path:

```
tom@asok:~/Projects/tomdavidson/s6$ tsviz src/ diagram.png
Found 9 module(s)
Done
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/local/bin/dot ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
tom@asok:~/Projects/tomdavidson/s6$ which dot
/usr/bin/dot

```
