### ISSUE TITLE
Error running tsviz

### ISSUE THREAD

**Issue by elouie99** [joaompneves/tsviz#43]
Running on MacOS High Sierra, with GraphViz installed and located correctly in /usr/local/bin, get this error:

ROSELCDV000256K:~ $ tsviz stash/data-query/src/nodes/ out.png
Found 37 module(s)
Done
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:792:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:617:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:794:10)

**Comment by Berkmann18** [comment]
I got a similar error in a VueJS project with _some_ TS components.
```
Found 5 module(s)
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:146:25)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at Socket._write (net.js:710:8)
    at doWrite (_stream_writable.js:417:12)
    at writeOrBuffer (_stream_writable.js:401:5)
    at Socket.Writable.write (_stream_writable.js:301:11)
    at exports.Graph.Graph.render (/home/maxie/.nvm/versions/node/v12.6.0/lib/node_modules/tsviz/node_modules/graphviz/lib/deps/graph.js:386:18)
    at exports.Graph.Graph.output (/home/maxie/.nvm/versions/node/v12.6.0/lib/node_modules/tsviz/node_modules/graphviz/lib/deps/graph.js:391:8)
    at Object.buildUml (/home/maxie/.nvm/versions/node/v12.6.0/lib/node_modules/tsviz/bin/uml-builder.js:30:7)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:432:5)
    at onwrite (_stream_writable.js:459:5)
    at internal/streams/destroy.js:49:7
    at Socket._destroy (net.js:595:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at afterWriteDispatched (internal/stream_base_commons.js:146:17)
    at writeGeneric (internal/stream_base_commons.js:137:3)
    at Socket._writeGeneric (net.js:698:11)
    at Socket._write (net.js:710:8) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
```
